### ISSUE TITLE
setup layouts.app

### ISSUE THREAD

**Issue by federicofrasca796** [federicofrasca796/git-training#1]
prepare html layout with yields to single pages content

**Comment by pollohultima** [comment]
I'll take it!

**Comment by federicofrasca796** [comment]
where?

**Comment by federicofrasca796** [comment]
watchout, you need to prepare @includes for partials!

**Comment by pollohultima** [comment]
Coglione

**Comment by pizzi9523** [comment]
licenziate pollo perchè non ha pullato 👺

**Comment by federicofrasca796** [comment]
A pollo, innanzitutto mortacci tua, dopodiché ti abbiamo cancellato la branch in remoto. Se devi riusarla, ricordati di ripusharla!!
MA SOPRATUTTO...PULLA CATHòN.
